### ISSUE TITLE
Behaviour when redefining attributes in Mixins

### ISSUE THREAD

**Issue by neonichu** [apiaryio/mson#23] opened 2015-05-20 15:53 UTC
Not sure if this is the right repo to talk about this, as it probably also relates to implementations. It seems like the behaviour when redefining attributes via Mixins is not defined at all. I have included the MSON I am talking about at the bottom of this to make it more readable.

Basically, I have two mixins which define the same attribute and its value is an object. My naive expectation (or maybe hope) was that the two object values would get merged, so that I would have one JSON dictionaries with values and keys of both those objects in the resulting JSON representation. What actually happens is that the value from the second mixin overwrites the first.

Is this considered to be the correct behaviour? If yes, is there a way to achieve the merging that I naively expected?

My MSON:

```markdown
### Content Type

- sys
    - type: ContentType - Type of Resource
    - id: 3ORKIAOaJqQWWg86MWkyOs - Identifier
    - version: 1 (number) - Version of Resource

### Content Type Creation

- name: Blog Post - Name of the Content Type
- fields (array[object]) - Defined Fields
    - (object)
        - id: title - Identifier of the Field
        - name: Title - Display name of the Field
        - type: Text - Type of the Field
    - (object)
        - id: body - Identifier of the Field
        - name: Body - Display name of the Field
        - type: Text - Type of the Field

### Content Type Published

- Include Content Type Creation
- Include Content Type
- Include Resource Published

### Resource Published

- sys - System Attributes
    - firstPublishedAt: `2015-05-15T13:38:11.311Z` - Date/time of first publishing
    - publishedCounter: 2 (number) - Number of times published
    - publishedAt: `2015-05-15T13:38:11.311Z` - Date/time of current publishing
    - publishedBy (User B)
    - publishedVersion: 9 (number) - Version of the resource that has been published
```

Resulting JSON:

```json
{
  "name": "Blog Post",
  "fields": [
    {
      "id": "title",
      "name": "Title",
      "type": "Text"
    },
    {
      "id": "body",
      "name": "Body",
      "type": "Text"
    }
  ],
  "sys": {
    "firstPublishedAt": "2015-05-15T13:38:11.311Z",
    "publishedCounter": 2,
    "publishedAt": "2015-05-15T13:38:11.311Z",
    "publishedBy": {
      "sys": {
        "type": "Link",
        "linkType": "User",
        "id": "4FLrUHftHW3v2BLi9fzfjU"
      }
    },
    "publishedVersion": 9
  }
}
```

Desired JSON:

```json
{
  "name": "Blog Post",
  "fields": [
    {
      "id": "title",
      "name": "Title",
      "type": "Text"
    },
    {
      "id": "body",
      "name": "Body",
      "type": "Text"
    }
  ],
  "sys": {
    "firstPublishedAt": "2015-05-15T13:38:11.311Z",
    "publishedCounter": 2,
    "publishedAt": "2015-05-15T13:38:11.311Z",
    "publishedBy": {
      "sys": {
        "type": "Link",
        "linkType": "User",
        "id": "4FLrUHftHW3v2BLi9fzfjU"
      }
    },
    "publishedVersion": 9,
    "type": "ContentType",
    "id": "3ORKIAOaJqQWWg86MWkyOs",
    "version": 1
  }
}
```

**Comment by zdne** [comment] 2015-05-21 02:13
Interesting – I believe the behavior is described here – [Member Type Precedence](https://github.com/apiaryio/mson/blob/master/MSON%20Specification.md#54-member-type-precedence).

In your case a solution would be to break it at the sys level I guess. 

But in reality – putting mixins aside – what would you expect here:

```markdown
- a: 42
- b: hello
- a: 32
```

vs 

```
- a
    - a1: 1
- a
    - a1: 2
    - a2: 2
```

?

**Comment by pksunkara** [comment] 2015-05-21 05:17
@neonichu Sorry but I have a small question regarding the JSON you wrote above. Is that the resultant JSON you want? Or is it the JSON returned by our tooling?

Can you add both the JSONs, the one you want and the one returned by our tooling?

**Comment by neonichu** [comment] 2015-05-21 09:32
@zdne Ah, I totally missed that section, sorry. 

My expectation would have been:

```json
{
  "a": 32,
  "b": "hello"
}
```

and

```json
{
  "a": {
    "a1" : 2,
    "a2": 2
  }
}
```

Basically a policy that would merge when possible (maybe also for arrays), but overwrite when necessary. It seems to me at least more suited to a mixin. On the other hand, I can also see how e.g. your second example gets a bit more confusing and might therefore lead to unexpected results.

@pksunkara sure, that was the JSON I got. I added a "Desired JSON" to the issue above.

**Comment by pksunkara** [comment] 2015-05-22 05:46
After looking at your desired JSON and resultant JSON, I can safely say that the resultant JSON is not a bug according to our MSON specification. Please read the section pointed out to you by @zdne to understand more about it.

That said, You can try to describe the MSON in a different way to get your desired JSON. I am closing this issue.

**Closed by pksunkara** 2015-05-22 05:46 UTC

**Comment by zdne** [comment] 2015-05-25 14:19
@neonichu 

> Basically a policy that would merge when possible (maybe also for arrays), but overwrite when necessary. 

This makes sense. The reason we went with current behavior is because we believed it is easier both to understand the rule and to implement.
