### ISSUE TITLE
Bug in Schema generation for Enum and Array

### ISSUE THREAD

**Issue by JAStanton** [apiaryio/mson#31] opened 2015-06-25 17:35 UTC
I have an enum of strings called `Notification Type`
I want to another object to have a property and the properties type is an array of `Notification Type`.

```md
## Notification Type (enum[string])
+ TYPE_A
+ TYPE_B
+ TYPE_C

## Notifications (object)
+ sms (array[Notification Type])
+ email (array[Notification Type])
```

or possibly
```md
## Notification Type (enum[string])
+ TYPE_A
+ TYPE_B
+ TYPE_C

## Notifications (object)
+ sms (array)
    + TYPE_A (Notification Type)
    + TYPE_B (Notification Type)
+ email (array)
    + TYPE_C (Notification Type)
```

Basically I want the generated schema to look like this:
```json
"notifications": {
  "email": {
    "type": "array",
    "items": {
      "type": "string",
      "enum": ["TYPE_A", "TYPE_B", "TYPE_C"]
    }
  },
  "sms": {
    "type": "array",
    "items": {
      "type": "string",
      "enum": ["TYPE_A", "TYPE_B", "TYPE_C"]
    }
  },
}
```

However when I try the first two options I get a schema that looks like this:
```json
"notifications": {
  "type": "object",
  "properties": {
    "sms": {
      "type": "array",
    },
    "email": {
      "type": "array",
    }
  }
}
```

**Comment by alexturek** [comment] 2015-06-25 20:50
This might be a bug in our team's parsing of the AST, not the AST generation. Details to follow

**Comment by alexturek** [comment] 2015-06-25 21:02
No sorry I'm wrong, this is showing up in aglio-generated JSON schema, so it has nothing to do with our code

**Comment by alexturek** [comment] 2015-06-25 21:18
This is also an issue for arrays of objects. So e.g.
```
## Foo (object)
- bar (number)
- baz (string)

## Foo List (array[Foo]) - A list of Foos
```

Emits a JSON schema for Foo List like
```
{
  "type": "array",
  "description": "A list of Foos"
}
```
Where I'd expect
```
{
  "type": "array",
  "description": "A list of Foos",
  "items": {
    "type": "object",
    "properties": {
      "bar": {
        "type": "string"
      },
      "baz": {
        "type": "string"
      }
    }
  }
}
```

**Comment by zdne** [comment] 2015-06-26 12:49
Apparently there is something now quite working with Drafter (Boutique) – the tool that is "rendering" JSON Schema from MSON (AST). 

Thanks for reporting. We will look into it!

**Comment by alexturek** [comment] 2015-07-21 20:36
This seems to be the actual implementation bug https://github.com/apiaryio/drafter/issues/47

**Comment by pksunkara** [comment] 2015-07-25 07:53
I am no sure it is actually since apiaryio/drafter#47 is about expanding nested arrays but this bug is about rendering the first level of arrays itself. Please stop linking other bugs. All of these are different.

**Comment by huiyiqun** [comment] 2015-07-28 07:16
There is both the cause and workaround for this issue: apiaryio/drafter.js#38

This is working but not perfect.
```apib
## Notifications (object)
+ sms (array)
    + (enum, fixed)
        + TYPE_A
        + TYPE_B
        + TYPE_C
+ email (array)
    + (enum, fixed)
        + TYPE_A
        + TYPE_B
        + TYPE_C
```

**Comment by erewh0n** [comment] 2015-08-12 13:31
+1 it would be great if we weren't forced to use the `fixed` type attribute in order to get the auto-generation of JSON schemas for objects nested in arrays.  This is a common use case for us and obviously not every field in nested objects are required.

**Comment by alexturek** [comment] 2015-09-03 04:17
`fixed` just doesn't solve our problem here. At least, not as currently implemented; it adds some really funky semantics to the API blueprint docs -> schema path

This apib...
```
# Data Structures

## Foo (object)
+ id: `t3f39f8c-c62f-4bcd-94f9-00e9a7780fed` (string, required) - The unique ID

# Group Foos

## All Foos [/foos]

### Retrieve Foos [GET]

Retrieve all Foos

+ Response 200 (application/json)
    + Attributes (object)
        + resources (array[Foo], fixed)
```
...generates this schema (note the `enum` for `id`)...
```
{
  "type": "object",
  "properties": {
    "resources": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "id": {
              "type": "string",
              "enum": [
                "t3f39f8c-c62f-4bcd-94f9-00e9a7780fed"
              ],
              "description": "The unique ID"
            }
          },
          "required": [
            "id"
          ]
        }
      ]
    }
  },
  "required": [
    "resources"
  ],
  "$schema": "http://json-schema.org/draft-04/schema#"
}
```

**Comment by nickarnold** [comment] 2015-09-04 04:15
+1 I have just experienced the issue that @alexturek has demonstrated above. So, apparently adding `fixed` is not the answer here as others have noted. 

JSON Schema auto-generation from Blueprint + embedded MSON is an essential feature for us since we rely on that auto-generated schema for use with our validators and we do not want to waste time writing MSON and the JSON Schema.

**Comment by petebrowne** [comment] 2015-10-16 21:42
What's the status of this? We're running into the same issue.

**Comment by zdne** [comment] 2015-10-19 16:04
@petebrowne it is scheduled (read not yet fixed)

**Comment by toinette** [comment] 2016-01-25 10:12
Waiting for this fix. Still working on it ?

**Comment by k-rudy** [comment] 2016-01-25 10:16
+1 for having this fixed, we're really suffering from this on our projects, as we use generated JSON schema in our tests suite.

**Comment by zdne** [comment] 2016-01-26 12:22
Hi, I believe this was fixed in the latest version of parser – [Drafter](https://github.com/apiaryio/drafter). @kylef can you please confirm?

**Comment by zdne** [comment] 2016-01-26 12:22
Note the fix HAS NOT been deployed to Apiary just yet (if you are using it)

**Comment by k-rudy** [comment] 2016-01-26 13:04
@zdne thanks for the update, do you have any information on when to expect it deployed to Apiary?

**Comment by pksunkara** [comment] 2016-01-26 13:12
I can confirm that this bug has been fixed in the latest parser. Unfortunately, it's still waiting to be deployed to Apiary.

**Comment by EBPTeam** [comment] 2016-02-05 08:27
Do you have an E.T.A. on the deployment of the latest parser to Apiary?

**Comment by zdne** [comment] 2016-02-05 14:10
cc @netmilk

**Comment by EBPTeam** [comment] 2016-02-08 11:00
Hey Z, I'm guessing Adam doesn't want to disclose the E.T.A. yet?!

**Comment by zdne** [comment] 2016-02-08 11:47
@EBPTeam I think it is being slowly rolled out right now. Check https://github.com/apiaryio/api-blueprint/issues/191#issuecomment-178044764

**Comment by sunnylion** [comment] 2016-02-19 12:51
Has this problem been fixed?

**Comment by sunnylion** [comment] 2016-02-19 12:52
What's the status of this problem?

**Comment by zdne** [comment] 2016-02-19 14:07
@sunnylion the new parser and renderer are being rolled out but unfortunately due to a regression issue the schema is not visible in the Apiary documentation at the moment. We are working on the fix.

**Comment by maciejmrowiec** [comment] 2016-03-02 13:23
+1 for fixing it

**Comment by zdne** [comment] 2016-03-02 16:24
Hey @maciejmrowiec the bug should be fixed in the latest instance of parser [drafter](https://github.com/apiaryio/drafter). 

It has been deployed to Apiary behind the feature switch I have mentioned [before](https://github.com/apiaryio/api-blueprint/issues/191#issuecomment-178044764)

![screen shot 2016-03-02 at 5 23 35 pm](https://cloud.githubusercontent.com/assets/613617/13466745/9571483e-e09b-11e5-82e3-3203083aa4d1.png)

**Comment by k-rudy** [comment] 2016-03-04 05:37
@zdne just to confirm - it's still not fixed in APIary yet from what I can see right now:

<img width="1177" alt="apiary_array" src="https://cloud.githubusercontent.com/assets/1032148/13518894/a707aeaa-e1e3-11e5-9215-481a56a63d30.png">

Array items are still not specified in schema and your screenshot above is about nested objects, not array. I don't understand how it's relevant to this issue. We're are all here interested in having this issue fixed so we expect someone to tell when the fix is deployed if that makes sense.

**Comment by pksunkara** [comment] 2016-03-04 10:12
@k-rudy As said [here](https://github.com/apiaryio/api-blueprint/issues/191#issuecomment-178044764), it has been deployed behind a feature switch which we are slowly rolling out.

**Comment by zdne** [comment] 2016-03-04 13:01
@k-rudy, @pksunkara, @maciejmrowiec 

Correction: This issue has not been fixed. Right now (with the feature switch) you have to add `fixed` to the `array` in order to get the `items` field in JSON Schema.

```apib
# Attributes Rendering 

# User [/user]
## Retrieve [GET]
- Response 200 (application/json)
    - Attributes (User)
        - name: Z
        - nested
            - a
            - b
            - c

# Collection of Users [/users]
## Retrieve [GET]
- Response 200 (application/json)
    - Attributes (object)
        - entries (array[User], fixed) - Array of user objects.

# Data Structures
## User
- name: John
```

I do apologize for the confusion.

**Comment by k-rudy** [comment] 2016-03-04 14:09
@zdne @pksunkara thanks for clarification. Appreciate that.

**Comment by beyourselfman** [comment] 2016-04-18 12:44
moved from here: https://github.com/apiaryio/dredd/issues/177

@w-vi I have trouble to follow your MAY-MUST argumentation. In my opinion the distinction in json schema between may and must is made by the `required` field. In the following example:

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string"
      },
      "fields": {
        "type": "object",
        "properties": {
          "field-a": {
            "type": "string"
          },
          "field-b": {
            "type": "string"
          }
        },
        "required": [
          "field-a"
        ]
      }
    },
    "required": [
      "name",
      "fields"
    ]
  }
}
```

This response should be valid

```
[
  {
    "name": "name",
    "fields": {
      "field-a": "value-a"      
    }
  }
]
```

This response should be not valid (error: `Invalid type. Expected String but got Integer.`)

```
[
  {
    "name": "name",
    "fields": {
      "field-a": 1    
    }
  }
]
```

What am I missing here? ;-)

**Comment by w-vi** [comment] 2016-04-18 14:10
@beyourselfman I'll repost here what @honzajavorek wrote in the above mentioned dredd issue so that we can continue here

Both JSON Schema and MSON take by default some things as required, others as optional. In both there are means to go out of the default behavior (i.e. `required`, `optional`, `additionalProperties`, `fixed`, ...). However, *mostly*, the default behavior in JSON Schema is to strictly *validate* given structure, whereas the default behavior MSON is usually to just *describe* what may appear in given structure. This is why MSON lacks some means to behave more strictly. One of these means is to strictly limit contents of arrays.

**Comment by pksunkara** [comment] 2016-07-18 13:35
I am closing this issue since the original bug has been fixed.

**Closed by pksunkara** 2016-07-18 13:35 UTC
Labels: e2: downstream, t2: bug

**Comment by k-rudy** [comment] 2016-07-27 16:14
@pksunkara, @zdne just to confirm: The original issue is not fixed.

Now if you don't supply `fixed` for the array item - the item content will not appear in schema.

But supplying `fixed` is not a proper fix like @alexturek shows [here](https://github.com/apiaryio/mson/issues/31#issuecomment-137326449). Because then all string, boolean and number types have `enum` property taken from the example value and the schema is still not usable. So I'm really not sure why this issue was closed.

**Comment by pksunkara** [comment] 2016-07-27 16:18
The original bug has been fixed and `fixed` is acting how we intended it to be. What you are talking about is something that MSON is lacking and thus can be classified as a feature request. In particular, this feature request is already being discussed at https://github.com/apiaryio/mson/issues/66. So, please follow it there.

**Comment by pksunkara** [comment] 2016-08-25 15:53
We have added support for `fixed-type` in https://github.com/apiaryio/mson/pull/67 and it is available in Drafter 3.1.0-pre.0. We will be releasing it soon.

**Comment by willdurand** [comment] 2016-10-27 17:15
Still experiencing this issue on apiary.io :( (workaround with `fixed` does work though)

**Comment by w-vi** [comment] 2016-10-27 18:27
@willdurand yes you can use `fixed-type` as well.

**Comment by willdurand** [comment] 2016-10-27 18:30
@w-vi thanks!
